config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "artists#index"

  resources :songs
  resources :artists
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :name, presence: true
  validates :album, presence: true
  validates :image_url, length: { maximum: 500 }, allow_blank: true, format: { with: %r{.(gif|jpg|png)\Z}i, message: 'must be a URL for GIF, JPG or PNG image.' }
  validates :duration, numericality: { only_integer: true }
  validates :duration, numericality: { less_than: 10000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
     @artist = Artist.find(params[:id])
     @artist.destroy
     redirect_to artists_path
  end

  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    @songs = Song.order(sort_column + " " + sort_direction)
  end

  
  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
       redirect_to @song
    else
       render 'new'
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
   @song = Song.find(params[:id])

   if @song.update_attributes(song_params)
     redirect_to @song
   else
     render 'edit'
   end
 end

 def destroy
    @song = Song.find(params[:id])

    @song.destroy

    redirect_to songs_path
  end

 private

 def song_params
   params.require(:song).permit(:name, :album, :image_url, :duration, :artist_id)
 end

 def sort_column
    Song.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end


end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <p><%= link_to artist.name, artist_path(artist.id) %></p>
<% end %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>
<p>
  <strong>Genre:</strong>
  <%= @artist.genre %>
</p>
<%= image_tag @artist.image_url %>

<h4>List of Songs</h4>



<% if @artist.songs.any? %>
  <ul>
    <% @artist.songs.each do |song| %>
        <p><%= link_to song.name, song_path(song.id) %></p>
    <% end %>
  </ul>
<% else %>
  <p>There are no songs for this artist.</p>
<% end %>

<%= link_to "[Add a new song]", new_song_path %>
<br><br>
<%= link_to "[Songs in alphabetical order]", songs_path %>
<br><br>
<hr>
<br>
<%= link_to "[Delete artist]", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br><br>
    <hr>
    
    <%= link_to "[All Artists]", root_path %>
  </body>
</html>

app/views/songs/_form.html.erb
<ul>
  <% @song.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<%= form_for @song do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :album %>
  <%= f.text_field :album %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.label :duration %>
  <%= f.number_field :duration%>

  <%= f.label :artist_id %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>

  <%= f.submit (@song.new_record? ? "Create" : "Update") %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Dinosaur</h1>

<%= render "form" %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<% @songs.each do |song| %>
  <p><%= song.name %></p>
<% end %>



  
  <th><%= sortable "name", "a-z/z-a" %></th>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form" %>

app/views/songs/show.html.erb
<h1><%= @song.name %></h1>

<p>album: <%= @song.album %></p>
<%= image_tag @song.image_url %>
<p>duration: <%= @song.duration %> seconds</p>

<%= link_to "[Delete]", song_path(@song.id), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "[Edit]", edit_song_path(@song.id) %>